# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0003_divorceform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorceform',
            name='assets',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='assets_before',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='children',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='custody',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='gender',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='mutual',
            field=models.CharField(max_length=250),
        ),
    ]
