# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0005_auto_20161019_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divorceform',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
