# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0006_auto_20161020_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='divorceform',
            name='casetype',
            field=models.CharField(default='divorce', max_length=250),
        ),
    ]
