# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-06 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawyered', '0009_auto_20161105_0557'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('utype', models.CharField(choices=[('c', 'Client'), ('l', 'Lawyer')], max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=250)),
                ('contact', models.IntegerField(default=0)),
                ('specialization', models.CharField(max_length=250)),
                ('bar_no', models.IntegerField(default=0)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='lawyered/media/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
