# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-08 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0011_auto_20161106_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_user',
            field=models.CharField(blank=True, choices=[('c', 'Client'), ('l', 'Lawyer')], max_length=250),
        ),
    ]
