# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0012_auto_20161108_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='details',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
