# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyered', '0013_auto_20161114_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criminalform',
            name='casetype',
            field=models.CharField(default='criminal', max_length=250),
        ),
        migrations.AlterField(
            model_name='divorceform',
            name='casetype',
            field=models.CharField(default='divorce', max_length=250),
        ),
        migrations.AlterField(
            model_name='duiform',
            name='casetype',
            field=models.CharField(default='dui', max_length=250),
        ),
        migrations.AlterField(
            model_name='estateform',
            name='casetype',
            field=models.CharField(default='estate', max_length=250),
        ),
        migrations.AlterField(
            model_name='mergerform',
            name='casetype',
            field=models.CharField(default='merger', max_length=250),
        ),
        migrations.AlterField(
            model_name='prenupform',
            name='casetype',
            field=models.CharField(default='prenup', max_length=250),
        ),
    ]
